<a href="https://colab.research.google.com/github/SathwikaSarabu/Books-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.rand(3,2)

array([[0.65640788, 0.37393252],
       [0.38290848, 0.86747109],
       [0.01110935, 0.1708587 ]])

In [6]:
np.random.randn(3,2)

array([[-0.63896007,  0.0157658 ],
       [ 0.48848242,  0.87240827],
       [ 0.01570426,  0.89671769]])

In [7]:
np.random.randint(1,5)

4

In [8]:
np.random.randint(34,100,30)

array([79, 77, 44, 85, 45, 49, 67, 82, 78, 54, 47, 42, 52, 55, 93, 82, 51,
       54, 82, 40, 83, 77, 81, 90, 53, 60, 68, 58, 95, 64])

In [9]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
rand_array=np.random.randint(0,100,20)
rand_array

array([64, 61,  7, 53, 51, 34, 13, 29, 57, 65, 97, 61, 19, 58, 37, 66, 91,
       35, 76, 96])

In [11]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [12]:
rand_array.min()

7

In [13]:
rand_array.argmin()

2

In [14]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
a=np.random.rand(2,3)
a

array([[0.08720954, 0.87278145, 0.00119322],
       [0.73944835, 0.07595001, 0.38833637]])

In [17]:
a.T

array([[0.08720954, 0.73944835],
       [0.87278145, 0.07595001],
       [0.00119322, 0.38833637]])

In [18]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
sample_array[3]

13

In [20]:
sample_array[1:7]

array([11, 12, 13, 14, 15, 16])

In [21]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [22]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [23]:
sample_array[:]

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [25]:
sample_matrix=np.array([[1,12,13,15],[5,4,23,21],[7,8,55,47]])
sample_matrix

array([[ 1, 12, 13, 15],
       [ 5,  4, 23, 21],
       [ 7,  8, 55, 47]])

In [26]:
sample_matrix[2]

array([ 7,  8, 55, 47])

In [27]:
sample_matrix[2,:]

array([ 7,  8, 55, 47])

In [28]:
sample_matrix[:,(3,2)]

array([[15, 13],
       [21, 23],
       [47, 55]])

In [29]:
sample_matrix[0:2,2]

array([13, 23])

In [30]:
sample_array+sample_array

array([ 20, 200, 200, 200,  28,  30,  32,  34,  36,  38,  40])

In [31]:
np.exp(sample_array)

array([2.20264658e+04, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [32]:
np.sqrt(sample_array)

array([ 3.16227766, 10.        , 10.        , 10.        ,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595])

In [33]:
np.square(sample_array)

array([  100, 10000, 10000, 10000,   196,   225,   256,   289,   324,
         361,   400])

In [34]:
np.min(sample_array)

10

In [35]:
np.argmin(sample_array)

0

In [36]:
np.max(sample_array)

100

In [37]:
np.argmax(sample_array)

1

In [38]:
np.log(sample_array)

array([2.30258509, 4.60517019, 4.60517019, 4.60517019, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [39]:
np.std(sample_array)

37.44086246092873

In [40]:
np.var(sample_array)

1401.8181818181818

In [41]:
np.mean(sample_array)

39.0

In [42]:
array=np.random.randn(3,4)
array

array([[ 1.45593877,  0.69289183,  1.74645456,  0.53930749],
       [-2.58815179,  1.05826904, -0.11484607, -0.55373061],
       [-1.49971366,  0.88231777,  0.66621071, -0.43318779]])

In [43]:
np.round(array,decimals=3)

array([[ 1.456,  0.693,  1.746,  0.539],
       [-2.588,  1.058, -0.115, -0.554],
       [-1.5  ,  0.882,  0.666, -0.433]])

In [44]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
sports

array(['golf', 'cricket', 'fball', 'cricket', 'fball', 'basketball'],
      dtype='<U10')

In [45]:
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')